/* config.h.  Generated by cmake from config.h.cmake  */

/* media HAL backend compilation */
#undef COMPILE_HALBACKEND

/* Define if covariant return in virtual methods works */
#cmakedefine HAVE_COVARIANT_RETURN 1

/* Define to 1 if you have the <Alib.h> header file. */
#cmakedefine HAVE_ALIB_H 1

/* Define if you have the CoreAudio API */
#undef HAVE_COREAUDIO

/* Define to 1 if you have the <devinfo.h> header file. */
#cmakedefine HAVE_DEVINFO_H 1

/* Define if you have DPMS support */
#cmakedefine HAVE_DPMS 1

/* Define if you have the DPMSCapable prototype in <X11/extensions/dpms.h> */
#cmakedefine HAVE_DPMSCAPABLE_PROTO 1

/* Define if you have the DPMSInfo prototype in <X11/extensions/dpms.h> */
#cmakedefine HAVE_DPMSINFO_PROTO 1

/* Defines if your system has the libfontconfig library */
#cmakedefine HAVE_FONTCONFIG 1

/* Define to 1 if you have the <fstab.h> header file. */
#cmakedefine HAVE_FSTAB_H 1

/* Define to 1 if you have the `getifaddrs' function. */
#cmakedefine HAVE_GETIFADDRS 1

/* Define to 1 if you have the `getloadavg' function. */
#cmakedefine HAVE_GETLOADAVG 1

/* Define to 1 if you have the `getnameinfo' function. */
#cmakedefine HAVE_GETNAMEINFO 1

/* Define to 1 if you have the `getpeereid' function. */
#cmakedefine HAVE_GETPEEREID 1

/* Define to 1 if you have the `getpt' function. */
#cmakedefine HAVE_GETPT 1


/* Define to 1 if you have the `grantpt' function. */
#cmakedefine HAVE_GRANTPT 1

/* Defines if you have Solaris' libkstat */
/* #undef HAVE_KSTAT */

/* Defines if you have libdevinfo of Solaris 7 or later */
#undef HAVE_LIBDEVINFO_H

/* Define to 1 if you have the <libutil.h> header file. */
#cmakedefine HAVE_LIBUTIL_H 1

/* Define to 1 if you have the <limits.h> header file. */
#cmakedefine HAVE_LIMITS_H 1

/* Define to 1 if you have the <linux/raw.h> header file. */
#cmakedefine HAVE_LINUX_RAW_H 1

/* Define if you have long long as datatype */
#define HAVE_LONG_LONG 1

/* Define to 1 if you have the <mntent.h> header file. */
#cmakedefine HAVE_MNTENT_H 1

/* Define to 1 if you have the `nice' function. */
#define HAVE_NICE 1

/* Defines whether we can use the openpty() function */
#cmakedefine HAVE_OPENPTY 1

/* Define to 1 if you have the <paths.h> header file. */
#cmakedefine HAVE_PATHS_H 1

/* Define to 1 if you have the <pty.h> header file. */
#cmakedefine HAVE_PTY_H 1

/* Define to 1 if you have the <sasl.h> header file. */
#cmakedefine HAVE_SASL_H 1

/* Define to 1 if you have the <sasl/sasl.h> header file. */
#cmakedefine HAVE_SASL_SASL_H 1

/* Define to 1 if you have the `setpriority' function. */
#cmakedefine HAVE_SETPRIORITY 1

/* Define to 1 if you have the `setproctitle' function. */
#cmakedefine HAVE_SETPROCTITLE 1

/* Define to 1 if you have the `sigaction' function. */
#define HAVE_SIGACTION 1

/* Define to 1 if you have the `sigset' function. */
#define HAVE_SIGSET 1

/* Define to 1 if you have the <string.h> header file. */
#cmakedefine HAVE_STRING_H 1

/* Define to 1 if you have the `strnlen' function. */
#cmakedefine HAVE_STRNLEN 1

/* Define to 1 if `sin6_len' is member of `struct sockaddr_in6'. */
#cmakedefine HAVE_STRUCT_SOCKADDR_IN6_SIN6_LEN

/* Define to 1 if `sin_len' is member of `struct sockaddr_in'. */
#cmakedefine HAVE_STRUCT_SOCKADDR_IN_SIN_LEN

/* Define to 1 if `sa_len' is member of `struct sockaddr'. */
#cmakedefine HAVE_STRUCT_SOCKADDR_SA_LEN

/* Define if you have the struct ucred */
#cmakedefine HAVE_STRUCT_UCRED 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#cmakedefine HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/loadavg.h> header file. */
#cmakedefine HAVE_SYS_LOADAVG_H 1

/* Define to 1 if you have the <sys/raw.h> header file. */
#cmakedefine HAVE_SYS_RAW_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#cmakedefine HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#cmakedefine HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/sockio.h> header file. */
#cmakedefine HAVE_SYS_SOCKIO_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#cmakedefine HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#cmakedefine HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#cmakedefine HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#cmakedefine HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#cmakedefine HAVE_TERMIOS_H 1

/* Define to 1 if you have the <termio.h> header file. */
#cmakedefine HAVE_TERMIO_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H 1

/* Define if you have usleep */
#cmakedefine HAVE_USLEEP 1

/* Define if you have the usleep prototype */
#cmakedefine HAVE_USLEEP_PROTO 1

/* Define to 1 if you have the <util.h> header file. */
#cmakedefine HAVE_UTIL_H 1

/* Define to 1 if you have the `vsnprintf' function. */
#cmakedefine HAVE_VSNPRINTF 1

/* Define if you have the XComposite extension */
#cmakedefine HAVE_XCOMPOSITE 1

/* Define to 1 if you have Xcursor */
#cmakedefine HAVE_XCURSOR 1

/* Define if you have the xf86misc extension */
#cmakedefine HAVE_XF86MISC 1

/* Define if you have the XFixes extension */
#cmakedefine HAVE_XFIXES 1

/* Defines if you have Xft */
#define HAVE_XFT 1

/* Define if you have the XKB extension */
#cmakedefine HAVE_XKB 1

/* Define if you have XkbSetPerClientControls */
#cmakedefine HAVE_XKBSETPERCLIENTCONTROLS 1

/* Defined if your system has XRender support */
#cmakedefine HAVE_XRENDER 1

/* Define if you have the XScreenSaver extension */
#cmakedefine HAVE_XSCREENSAVER 1

/* Define if you have the XTest extension */
#cmakedefine HAVE_XTEST 1

/* KDE's binaries directory */
#define KDE_BINDIR "${CMAKE_INSTALL_PREFIX}/bin"

/* KDE's configuration directory */
#define KDE_CONFDIR "${CMAKE_INSTALL_PREFIX}/share/config"

/* KDE's static data directory */
#define KDE_DATADIR "${CMAKE_INSTALL_PREFIX}/share/apps"

/* Use mallinfo field hblkhd */
#define KDE_MALLINFO_FIELD_hblkhd 1

/* Use mallinfo field uordblks */
#define KDE_MALLINFO_FIELD_uordblks 1

/* Use mallinfo field usmblks */
/* #undef KDE_MALLINFO_FIELD_usmblks */

/* mallinfo() is available in <malloc.h> */
#cmakedefine KDE_MALLINFO_MALLOC 1

/* mallinfo() is available in <stdlib.h> */
#cmakedefine KDE_MALLINFO_STDLIB 1

/* Name of package */
#define PACKAGE "kdebase"

/* Define where your java executable is */
#undef PATH_JAVA

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG ${SIZEOF_LONG}

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#cmakedefine TIME_WITH_SYS_TIME 1

/* Define the file for utmp entries */
#define UTMP "${UTMP_FILE}"

/* Version number of package */
#define VERSION "3.9.02"

/* X binaries directory */
#define XBINDIR "/usr/X11R6/bin"

/* X libraries directory */
#define XLIBDIR "/usr/X11R6/lib/X11"

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64


#if !defined(HAVE_USLEEP_PROTO)
#ifdef __cplusplus
extern "C" {
#endif
int usleep (unsigned int);
#ifdef __cplusplus
}
#endif
#endif


/*
 * On HP-UX, the declaration of vsnprintf() is needed every time !
 */

#if !defined(HAVE_VSNPRINTF) || defined(hpux)
#if __STDC__
#include <stdarg.h>
#include <stdlib.h>
#else
#include <varargs.h>
#endif
#ifdef __cplusplus
extern "C"
#endif
int vsnprintf(char *str, size_t n, char const *fmt, va_list ap);
#ifdef __cplusplus
extern "C"
#endif
int snprintf(char *str, size_t n, char const *fmt, ...);
#endif



#if defined(__SVR4) && !defined(__svr4__)
#define __svr4__ 1
#endif

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */

/* type to use in place of socklen_t if not defined */
#define kde_socklen_t socklen_t
