#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

#from Object import createObj

pics_eng = """
./en/8020.png
./en/afterDistribution.png
./en/aide.png
./en/annuler.png
./en/attackOne.png
./en/attack.png
./en/attackThree.png
./en/attackTwo.png
./en/belgium.png
./en/cannon.png
./en/cavalry.png
./en/defendOne.png
./en/defendTwo.png
./en/distributionArmeesFinie.png
./en/distributionArmees.png
./en/exploding.png
./en/firing.png
./en/france.png
./en/infantry.png
./en/italy.png
./en/japan.png
./en/joueurSuivant.png
./en/logoLeft.png
./en/logoRight.png
./en/map-mask.png
./en/map.png
./en/moveArmies.png
./en/moveBackFive.png
./en/moveBackOne.png
./en/moveBackTen.png
./en/moveFinish.png
./en/moveFive.png
./en/movement.png
./en/moveOne.png
./en/moveTen.png
./en/newNetGame.png
./en/nouveauJeu.png
./en/ouvrirJeu.png
./en/player1PlacingArmies.png
./en/quitter.png
./en/saveGame.png
./en/SoldatAGenoux1.png
./en/uk.png
./en/us.png
"""

obj=bld.create_obj('kde_documentation', 'ksirk', 'en')
obj.add_docs('en/index.docbook' + pics_eng)


