#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

#from Object import createObj
obj = bld.create_obj('kde', 'shlib')
obj.source = """
aiColsonPlayer.cpp
aiplayer.cpp
aiplayerio.cpp
continent.cpp
country.cpp
dice.cpp
eventslistproperty.cpp
gameautomaton.cpp
goal.cpp
KsirkChatItem.cpp
KMessageParts.cpp
nationality.cpp
onu.cpp
player.cpp
"""

obj.uselib = 'QT KDECORE'
obj.target = 'ksirk_gamelogic'
obj.includes = '.  .. ../../kgame-patch ../Dialogs ../GameLogic ../SaveLoad ../Sprites'

